version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: inflearn-clone-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - inflearn_clone_db:/var/lib/postgresql

volumes:
  inflearn_clone_db:
